Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          'DIU.Grid': ['*','NodeTypes/*']
    nodeTypes:
      groups:
        structure:
          position: 200
          label: Structure
          collapsed: true
    fusion:
      autoInclude:
        'DIU.Grid': true
  Fusion:
    defaultContext:
      'DIU.Grid' : 'DIU\Grid\Eel\Helper\GridHelper'
